name: application build

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: azure/docker-login@v2
      with:
        login-server: akserpdemacr01.azurecr.io
        username: AKSERPDEMACR01
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
       docker build . -t akserpdemacr01.azurecr.io/ERP:${{ github.sha }}
       docker push akserpdemacr01.azurecr.io/ERP:${{ github.sha }}
